export default function handler(req, res) {
    res.status(200).json({
        "847303": { city: "Jogiara", district: "Darbhanga", state: "Bihar" },
        "847230": { city: "Jale", district: "Darbhanga", state: "Bihar" },
        "847402": { city: "Madhubani", district: "Madhubani", state: "Bihar" },
        "847234": { city: "Benipur", district: "Darbhanga", state: "Bihar" },
        "847401": { city: "Jaynagar", district: "Madhubani", state: "Bihar" },
        "847109": { city: "Laheriasarai", district: "Darbhanga", state: "Bihar" },
        "847222": { city: "Biraul", district: "Darbhanga", state: "Bihar" },
        "847108": { city: "Bahadurpur", district: "Darbhanga", state: "Bihar" },
        "847308": { city: "Kiratpur", district: "Darbhanga", state: "Bihar" },
        "847211": { city: "Keoti", district: "Darbhanga", state: "Bihar" },
        "847212": { city: "Ghanshyampur", district: "Darbhanga", state: "Bihar" },
        "847213": { city: "Hanuman Nagar", district: "Darbhanga", state: "Bihar" },
        "847232": { city: "Sakri", district: "Darbhanga", state: "Bihar" },
        "847227": { city: "Manigachhi", district: "Darbhanga", state: "Bihar" },
        "847226": { city: "Alinagar", district: "Darbhanga", state: "Bihar" },
        "847224": { city: "Tardih", district: "Darbhanga", state: "Bihar" },
        "847229": { city: "Baheri", district: "Darbhanga", state: "Bihar" },
        "847231": { city: "Shivajinagar", district: "Darbhanga", state: "Bihar" },
        "847409": { city: "Laukaha", district: "Madhubani", state: "Bihar" },
        "846001": { city: "Darbhanga", district: "Darbhanga", state: "Bihar" },
        "846002": { city: "Mirdha Toli", district: "Darbhanga", state: "Bihar" },
        "846003": { city: "Allalpatti", district: "Darbhanga", state: "Bihar" },
        "846004": { city: "Benta", district: "Darbhanga", state: "Bihar" },
        "846005": { city: "Kabirchak", district: "Darbhanga", state: "Bihar" },
        "847101": { city: "Darbhanga RS", district: "Darbhanga", state: "Bihar" },
        "847103": { city: "Donar", district: "Darbhanga", state: "Bihar" },
        "847104": { city: "Lohia Nagar", district: "Darbhanga", state: "Bihar" },
        "847105": { city: "Lalit Narayan Mithila University", district: "Darbhanga", state: "Bihar" },
        "847115": { city: "Bhalpatti", district: "Darbhanga", state: "Bihar" },
        "847122": { city: "Sihora", district: "Darbhanga", state: "Bihar" },
        "847121": { city: "Pandaul", district: "Madhubani", state: "Bihar" },
        "847203": { city: "Rajnagar", district: "Madhubani", state: "Bihar" },
        "847204": { city: "Khajauli", district: "Madhubani", state: "Bihar" },
        "847301": { city: "Samastipur", district: "Samastipur", state: "Bihar" },
        "847302": { city: "Rosera", district: "Samastipur", state: "Bihar" },
        "847304": { city: "Patori", district: "Samastipur", state: "Bihar" },
        "847306": { city: "Dalsinghsarai", district: "Samastipur", state: "Bihar" },
        "847307": { city: "Shivajinagar", district: "Samastipur", state: "Bihar" },
        "847337": { city: "Kalyanpur", district: "Samastipur", state: "Bihar" },
        "848213": { city: "Mohiuddin Nagar", district: "Samastipur", state: "Bihar" },
        "848209": { city: "Hasanpur", district: "Samastipur", state: "Bihar" },
        "848205": { city: "Vidyapati Nagar", district: "Samastipur", state: "Bihar" },
        "800001": { city: "Patna GPO", district: "Patna", state: "Bihar" },
        "800002": { city: "Bankipore", district: "Patna", state: "Bihar" },
        "800003": { city: "Phulwari Sharif", district: "Patna", state: "Bihar" },
        "800004": { city: "Gulzarbagh", district: "Patna", state: "Bihar" },
        "800007": { city: "Kankarbagh", district: "Patna", state: "Bihar" },
        "800008": { city: "Rajendra Nagar", district: "Patna", state: "Bihar" },
        "800009": { city: "Danapur", district: "Patna", state: "Bihar" },
        "800010": { city: "Kumhrar", district: "Patna", state: "Bihar" },
        "800011": { city: "Fatuha", district: "Patna", state: "Bihar" },
        "800012": { city: "Didarganj", district: "Patna", state: "Bihar" },
        "800013": { city: "Pahari", district: "Patna", state: "Bihar" },
        "800014": { city: "Jagdishpur", district: "Patna", state: "Bihar" },
        "800015": { city: "Bailey Road", district: "Patna", state: "Bihar" },
        "800016": { city: "Khagaul", district: "Patna", state: "Bihar" },
        "800018": { city: "Anisabad", district: "Patna", state: "Bihar" },
        "800020": { city: "Ashiana Nagar", district: "Patna", state: "Bihar" },
        "800023": { city: "Patna City", district: "Patna", state: "Bihar" },
        "800024": { city: "Sadikpur", district: "Patna", state: "Bihar" },

        "801101": { city: "Bihta", district: "Patna", state: "Bihar" },
        "801103": { city: "Khagaul", district: "Patna", state: "Bihar" },
        "801104": { city: "Naubatpur", district: "Patna", state: "Bihar" },
        "801105": { city: "Paliganj", district: "Patna", state: "Bihar" },
        "801108": { city: "Masaurhi", district: "Patna", state: "Bihar" },

        "803201": { city: "Bihar Sharif", district: "Nalanda", state: "Bihar" },
        "803202": { city: "Barh", district: "Patna", state: "Bihar" },
        "803211": { city: "Harnaut", district: "Nalanda", state: "Bihar" },
        "803213": { city: "Chandi", district: "Nalanda", state: "Bihar" },
        "803214": { city: "Hilsa", district: "Nalanda", state: "Bihar" },
        "803302": { city: "Bakhtiyarpur", district: "Patna", state: "Bihar" },

        "804451": { city: "Jehanabad", district: "Jehanabad", state: "Bihar" },
        "804452": { city: "Kurtha", district: "Arwal", state: "Bihar" },
        "804453": { city: "Kako", district: "Jehanabad", state: "Bihar" },
        "804454": { city: "Makhdumpur", district: "Jehanabad", state: "Bihar" },

        "811302": { city: "Begusarai", district: "Begusarai", state: "Bihar" },

        "847408": { city: "Madhepur", district: "Madhubani", state: "Bihar" },
        "847403": { city: "Phulparas", district: "Madhubani", state: "Bihar" },
        "847404": { city: "Basopatti", district: "Madhubani", state: "Bihar" }
    });
}
